apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: ${{ values.project_name | lower | replace(" ", "-") }}
  description: AWS EKS platform project

spec:
  type: service
  lifecycle: experimental
  owner: group:platform-team
