apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: ${{ values.project_name }}
  description: AWS EKS platform project

spec:
  type: service
  lifecycle: experimental
  owner: guests
